/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.ControladorInformacion;
import Controlador.ControladorArchivos;
import Modelo.RegistroArchivos;
import java.awt.event.ActionListener;
import java.awt.event.ComponentListener;
import javax.swing.JTextArea;
/**
 *
 * @author peque
 */
public class GuiBuscar extends javax.swing.JFrame {
ControladorInformacion informacion;
RegistroArchivos registro;
    /**
     * Creates new form guiBuscar
     */
    public GuiBuscar(RegistroArchivos registro) {
        initComponents();
        this.informacion=new ControladorInformacion(this,registro);
        
        escucharInformacion(informacion);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jCargarInformacion = new javax.swing.JTextArea();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCargarInformacion.setColumns(20);
        jCargarInformacion.setRows(5);
        jCargarInformacion.setEnabled(false);
        jScrollPane1.setViewportView(jCargarInformacion);

        btnBuscar.setText("Buscar");

        btnSalir.setText("Salir");

        jLabel1.setFont(new java.awt.Font("Ubuntu Medium", 2, 24)); // NOI18N
        jLabel1.setText("Busqueda de archivos y carpeta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnSalir))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextArea jCargarInformacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
public static final String BTN_BUSCAR="Buscar";
public static final String BTN_SALIR="Salir";

public void escucharInformacion(ActionListener informacion){
    this.btnBuscar.addActionListener(informacion);
    this.btnSalir.addActionListener(informacion);
    
   // this.jCargarInformacion.addComponentListener((ComponentListener) informacion);
}

    public String getjCargarInformacion() {
        return jCargarInformacion.getText();
    }

    public void setjCargarInformacion(String Informacion) {
        this.jCargarInformacion.setText(Informacion);
    }

}
